#!/bin/bash -eu

enabled() { type $1 > /dev/null 2>&1; }
require() { if ! enabled $1; then echo "Please install $1."; exit 1; fi }

require git

DIR=$HOME/.dotfiles
XDG_CONFIG_HOME=$HOME/.config
mkdir -p $XDG_CONFIG_HOME

if ! [ -d $DIR ]; then
  git clone https://github.com/hoto17296/dotfiles.git $DIR
fi

if ! enabled brew; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
brew bundle install --file $DIR/setup/Brewfile

dotalias() { if ! [ -L $HOME/.$1 ]; then ln -s $DIR/$1 $HOME/.$1; fi }
dotcopy() { if ! [ -L $HOME/.$1 ]; then cp $DIR/$1 $HOME/.$1; fi }

dotalias hyper.js
dotalias ssh
dotalias gemrc
dotcopy  npmrc

ln -s $DIR/git $XDG_CONFIG_HOME/git

ln -s $DIR/peco $XDG_CONFIG_HOME/peco

require ghq
ghq get https://github.com/hoto17296/hypercwd.git
HYPER_LOCAL_PLUGIN_DIR=${HOME}/.hyper_plugins/local
mkdir -p ${HYPER_LOCAL_PLUGIN_DIR}
ln -s $(ghq root)/github.com/hoto17296/hypercwd ${HYPER_LOCAL_PLUGIN_DIR}/hypercwd

ghq get https://github.com/hoto17296/bin.git

VSCODE_DIR=$HOME/Library/Application\ Support/Code/User
\rm -f $VSCODE_DIR/keybindings.json
ln -s $DIR/vscode/keybindings.json $VSCODE_DIR/keybindings.json
\rm -f $VSCODE_DIR/settings.json
ln -s $DIR/vscode/settings.json $VSCODE_DIR/settings.json

mkdir -p $XDG_CONFIG_HOME/karabiner
\rm -f $XDG_CONFIG_HOME/karabiner/karabiner.json
ln -s $DIR/karabiner.json $XDG_CONFIG_HOME/karabiner/karabiner.json

mkdir -p ${HOME}/Notebooks
JUPYTER_CONFIG_DIR=${XDG_CONFIG_HOME}/jupyter
mkdir -p ${JUPYTER_CONFIG_DIR}
ln -s ${DIR}/jupyter-app ${JUPYTER_CONFIG_DIR}/app

require nvim
ln -s $DIR/nvim $XDG_CONFIG_HOME/nvim
DEIN_DIR=$HOME/.cache/dein/repos/github.com/Shougo/dein.vim
if ! [ -d $DEIN_DIR ]; then
  git clone https://github.com/Shougo/dein.vim.git $DEIN_DIR
fi

HACKGEN_VERSION=v2.3.2
TMP_FILE=hackgen.zip
wget -O ${TMP_FILE} https://github.com/yuru7/HackGen/releases/download/${HACKGEN_VERSION}/HackGen_${HACKGEN_VERSION}.zip
unzip ${TMP_FILE}
cp HackGen_${HACKGEN_VERSION}/HackGen35-{Regular,Bold}.ttf ${HOME}/Library/Fonts
rm -rf ${TMP_FILE} HackGen_${HACKGEN_VERSION}

/usr/bin/pip3 install --user ipython

require zsh
dotalias zsh
dotalias zshrc

SCREEN_CAPTURES_DIR=$HOME/Pictures/Screen\ Captures
mkdir -p $SCREEN_CAPTURES_DIR
defaults write com.apple.screencapture location $SCREEN_CAPTURES_DIR
