#!/bin/bash -eu

enabled() { type $1 > /dev/null 2>&1; }
require() { if ! enabled $1; then echo "Please install $1."; exit 1; fi }

require git

DIR=$HOME/.dotfiles

if ! [ -d $DIR ]; then
	git clone https://github.com/hoto17296/dotfiles.git $DIR
fi

if ! enabled brew; then
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
sh $DIR/setup/Brewfile.sh

dotalias() { if ! [ -L $HOME/.$1 ]; then ln -s $DIR/$1 $HOME/.$1; fi }
dotcopy() { if ! [ -L $HOME/.$1 ]; then cp $DIR/$1 $HOME/.$1; fi }

dotalias hyper.js
dotalias gitconfig
dotalias gitignore
dotalias ssh
dotalias gemrc
dotcopy  npmrc
dotalias peco

VSCODE_DIR=$HOME/Library/Application\ Support/Code/User
ln -s $DIR/vscode/keybingings.json $VSCODE_DIR/keybingings.json
ln -s $DIR/vscode/settings.json $VSCODE_DIR/settings.json

mkdir -p $HOME/.config/karabiner
ln -s $DIR/karabiner.json $HOME/.config/karabiner/karabiner.json

mkdir -p $HOME/notebooks
ln -s $DIR/jupyter-app $HOME/.config/jupyter-app

require nvim
ln -s $DIR/nvim $HOME/.config/nvim
DEIN_DIR=$HOME/.cache/dein/repos/github.com/Shougo/dein.vim
if ! [ -d $DEIN_DIR ]; then
  git clone https://github.com/Shougo/dein.vim.git $DEIN_DIR
fi

require zsh
dotalias zsh
dotalias zshrc
chsh -s `which zsh`
