#!/bin/sh

set -eu

enabled() { type $1 > /dev/null 2>&1; }
require() { if ! enabled $1; then echo "Please install $1."; exit 1; fi }

require git

DIR=$HOME/.dotfiles

if ! [ -d $DIR ]; then
	git clone https://github.com/hoto17296/dotfiles.git $DIR
fi

if ! enabled brew; then
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
#sh $DIR/setup/Brewfile.sh

if ! [ -d ~/.anyenv ]; then
  git clone https://github.com/riywo/anyenv ~/.anyenv
fi

dotalias() { if ! [ -L $HOME/.$1 ]; then ln -s $DIR/$1 $HOME/.$1; fi }

dotalias vimperator
dotalias vimperatorrc
dotalias gitconfig
dotalias gitignore
dotalias gemrc
#dotalias npmrc
dotalias peco
dotalias rbenv

require vim
BUNDLE=$HOME/.vim/bundle
dotalias vimrc
mkdir -p $BUNDLE
git clone https://github.com/Shougo/neobundle.vim $BUNDLE/neobundle.vim
$BUNDLE/neobundle.vim/bin/neoinstall

require zsh
dotalias zsh
dotalias zshrc
dotalias zshrc.osx
dotalias zshrc.peco
chsh -s `which zsh`
